"""Adaptive MCP tools for domain: Audit Logs.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to
change a tool, edit the generator (or the source OpenAPI spec) and regenerate via:
    python scripts/generate_from_openapi.py

Each generated tool is a thin async wrapper: it accepts typed parameters (path
params interpolated into the URL, query params forwarded as the query string) and
calls `execute_request`, which performs the actual HTTP GET.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP) -> None:
    # getAuditLog (GET /v2/audit-logs/{auditLogId}) — tool name "get_audit_log"
    @mcp.tool(name="get_audit_log", description="Get audit log details GET /v2/audit-logs/{auditLogId}. Params: auditLogId.")
    async def get_audit_log(
        auditLogId: Annotated[str, Field(description="Path param: auditLogId (string)")],
    ) -> Any:
        return await execute_request(f"/v2/audit-logs/{auditLogId}")

    # listAuditLogs (GET /v2/audit-logs) — tool name "list_audit_logs"
    @mcp.tool(name="list_audit_logs", description="List audit logs GET /v2/audit-logs. Params: page_after, page_size, start_date, end_date, actions.")
    async def list_audit_logs(
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=100, description="Query param: page_size (integer)")] = 100,
        start_date: Annotated[str | None, Field(default=None, description="Query param: start_date (string)")] = None,
        end_date: Annotated[str | None, Field(default=None, description="Query param: end_date (string)")] = None,
        actions: Annotated[list | None, Field(default=None, description="Query param: actions (array)")] = None,
    ) -> Any:
        return await execute_request("/v2/audit-logs", {"page_after": page_after, "page_size": page_size, "start_date": start_date, "end_date": end_date, "actions": actions})
