"""Adaptive MCP tools for domain: Groups.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to
change a tool, edit the generator (or the source OpenAPI spec) and regenerate via:
    python scripts/generate_from_openapi.py

Each generated tool is a thin async wrapper: it accepts typed parameters (path
params interpolated into the URL, query params forwarded as the query string) and
calls `execute_request`, which performs the actual HTTP GET.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP) -> None:
    # getGroup (GET /v2/groups/{groupId}) — tool name "get_group"
    @mcp.tool(name="get_group", description="Get group details GET /v2/groups/{groupId}. Params: groupId.")
    async def get_group(
        groupId: Annotated[str, Field(description="Path param: groupId (string)")],
    ) -> Any:
        return await execute_request(f"/v2/groups/{groupId}")

    # getGroupMembers (GET /v2/groups/{groupId}/users) — tool name "get_group_members"
    @mcp.tool(name="get_group_members", description="Get group users GET /v2/groups/{groupId}/users. Params: groupId, page_after, page_size.")
    async def get_group_members(
        groupId: Annotated[str, Field(description="Path param: groupId (string)")],
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=100, description="Query param: page_size (integer)")] = 100,
    ) -> Any:
        return await execute_request(f"/v2/groups/{groupId}/users", {"page_after": page_after, "page_size": page_size})

    # listGroups (GET /v2/groups) — tool name "list_groups"
    @mcp.tool(name="list_groups", description="List groups GET /v2/groups. Params: page_after, page_size.")
    async def list_groups(
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=50, description="Query param: page_size (integer)")] = 50,
    ) -> Any:
        return await execute_request("/v2/groups", {"page_after": page_after, "page_size": page_size})
