"""Adaptive MCP tools for domain: Phishing.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to
change a tool, edit the generator (or the source OpenAPI spec) and regenerate via:
    python scripts/generate_from_openapi.py

Each generated tool is a thin async wrapper: it accepts typed parameters (path
params interpolated into the URL, query params forwarded as the query string) and
calls `execute_request`, which performs the actual HTTP GET.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP) -> None:
    # getPhishingCampaign (GET /v2/phishing/campaigns/{campaignId}) — tool name "get_phishing_campaign"
    @mcp.tool(name="get_phishing_campaign", description="Get phishing campaign details GET /v2/phishing/campaigns/{campaignId}. Params: campaignId.")
    async def get_phishing_campaign(
        campaignId: Annotated[str, Field(description="Path param: campaignId (string)")],
    ) -> Any:
        return await execute_request(f"/v2/phishing/campaigns/{campaignId}")

    # getPhishingEnrollments (GET /v2/phishing/campaigns/enrollments) — tool name "get_phishing_enrollments"
    @mcp.tool(name="get_phishing_enrollments", description="Get phishing enrollments GET /v2/phishing/campaigns/enrollments. Params: user_id, campaign_id, simulation_id, page_after, page_size.")
    async def get_phishing_enrollments(
        user_id: Annotated[str | None, Field(default=None, description="Query param: user_id (string)")] = None,
        campaign_id: Annotated[str | None, Field(default=None, description="Query param: campaign_id (string)")] = None,
        simulation_id: Annotated[str | None, Field(default=None, description="Query param: simulation_id (string)")] = None,
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=50, description="Query param: page_size (integer)")] = 50,
    ) -> Any:
        return await execute_request("/v2/phishing/campaigns/enrollments", {"user_id": user_id, "campaign_id": campaign_id, "simulation_id": simulation_id, "page_after": page_after, "page_size": page_size})

    # getSimulation (GET /v2/phishing/simulations/{simulationId}) — tool name "get_simulation"
    @mcp.tool(name="get_simulation", description="Get simulation execution details GET /v2/phishing/simulations/{simulationId}. Params: simulationId.")
    async def get_simulation(
        simulationId: Annotated[str, Field(description="Path param: simulationId (string)")],
    ) -> Any:
        return await execute_request(f"/v2/phishing/simulations/{simulationId}")

    # listCampaignSimulations (GET /v2/phishing/campaigns/{campaignId}/simulations) — tool name "list_campaign_simulations"
    @mcp.tool(name="list_campaign_simulations", description="List simulations for campaign GET /v2/phishing/campaigns/{campaignId}/simulations. Params: campaignId, page_after, page_size.")
    async def list_campaign_simulations(
        campaignId: Annotated[str, Field(description="Path param: campaignId (string)")],
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=50, description="Query param: page_size (integer)")] = 50,
    ) -> Any:
        return await execute_request(f"/v2/phishing/campaigns/{campaignId}/simulations", {"page_after": page_after, "page_size": page_size})

    # listPhishingCampaigns (GET /v2/phishing/campaigns) — tool name "list_phishing_campaigns"
    @mcp.tool(name="list_phishing_campaigns", description="List phishing campaigns GET /v2/phishing/campaigns. Params: page_after, page_size.")
    async def list_phishing_campaigns(
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=50, description="Query param: page_size (integer)")] = 50,
    ) -> Any:
        return await execute_request("/v2/phishing/campaigns", {"page_after": page_after, "page_size": page_size})
