"""Adaptive MCP tools for domain: Training.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to
change a tool, edit the generator (or the source OpenAPI spec) and regenerate via:
    python scripts/generate_from_openapi.py

Each generated tool is a thin async wrapper: it accepts typed parameters (path
params interpolated into the URL, query params forwarded as the query string) and
calls `execute_request`, which performs the actual HTTP GET.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP) -> None:
    # getTrainingCampaign (GET /v2/training/campaigns/{campaignId}) — tool name "get_training_campaign"
    @mcp.tool(name="get_training_campaign", description="Get training campaign details GET /v2/training/campaigns/{campaignId}. Params: campaignId.")
    async def get_training_campaign(
        campaignId: Annotated[str, Field(description="Path param: campaignId (string)")],
    ) -> Any:
        return await execute_request(f"/v2/training/campaigns/{campaignId}")

    # getTrainingCampaignEnrollments (GET /v2/training/campaigns/enrollments) — tool name "get_training_campaign_enrollments"
    @mcp.tool(name="get_training_campaign_enrollments", description="Get training campaign enrollments details GET /v2/training/campaigns/enrollments. Params: user_id, campaign_id, page_after, page_size.")
    async def get_training_campaign_enrollments(
        user_id: Annotated[str | None, Field(default=None, description="Query param: user_id (string)")] = None,
        campaign_id: Annotated[str | None, Field(default=None, description="Query param: campaign_id (string)")] = None,
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=100, description="Query param: page_size (integer)")] = 100,
    ) -> Any:
        return await execute_request("/v2/training/campaigns/enrollments", {"user_id": user_id, "campaign_id": campaign_id, "page_after": page_after, "page_size": page_size})

    # listTrainingCampaigns (GET /v2/training/campaigns) — tool name "list_training_campaigns"
    @mcp.tool(name="list_training_campaigns", description="List training campaigns GET /v2/training/campaigns. Params: page_after, page_size.")
    async def list_training_campaigns(
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=100, description="Query param: page_size (integer)")] = 100,
    ) -> Any:
        return await execute_request("/v2/training/campaigns", {"page_after": page_after, "page_size": page_size})
