"""Adaptive MCP tools for domain: Users.

GENERATED by scripts/generate_from_openapi.py — DO NOT EDIT BY HAND.
Any manual change here will be overwritten the next time the generator runs; to
change a tool, edit the generator (or the source OpenAPI spec) and regenerate via:
    python scripts/generate_from_openapi.py

Each generated tool is a thin async wrapper: it accepts typed parameters (path
params interpolated into the URL, query params forwarded as the query string) and
calls `execute_request`, which performs the actual HTTP GET.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastmcp import FastMCP
from pydantic import Field

from .._common import execute_request


def register(mcp: FastMCP) -> None:
    # getUser (GET /v2/users/{userId}) — tool name "get_user"
    @mcp.tool(name="get_user", description="Get user details GET /v2/users/{userId}. Params: userId.")
    async def get_user(
        userId: Annotated[str, Field(description="Path param: userId (string)")],
    ) -> Any:
        return await execute_request(f"/v2/users/{userId}")

    # listUsers (GET /v2/users) — tool name "list_users"
    @mcp.tool(name="list_users", description="List users GET /v2/users. Params: page_after, page_size.")
    async def list_users(
        page_after: Annotated[str | None, Field(default=None, description="Query param: page_after (string)")] = None,
        page_size: Annotated[int | None, Field(default=100, description="Query param: page_size (integer)")] = 100,
    ) -> Any:
        return await execute_request("/v2/users", {"page_after": page_after, "page_size": page_size})
